# 🎓 AI Bootcamp Practice Exercises
## Week 3 - Day 1: NumPy Fundamentals

---

### 📚 Topics Covered Today:
- Difference between NumPy arrays and Python lists
- Array creation, indexing, slicing, and reshaping
- Element-wise operations and broadcasting
- Linear algebra with NumPy (dot product, matrix multiplication)
- Useful functions: reshape, concatenate, split

---

### 📝 Instructions:
- Read each **Example** carefully before attempting exercises
- Fill in the **TODO** sections with your code
- Run each cell to check your output
- Expected outputs are provided for reference
- Ask for help if you get stuck!

---

**Let's get started! 🚀**

---
## 🔹 Section 1: Introduction & Setup

NumPy (Numerical Python) is the fundamental package for scientific computing in Python. It provides:
- Fast and efficient multidimensional array operations
- Mathematical functions for arrays
- Tools for working with linear algebra, random numbers, and more

**Why NumPy?**
- 🚀 **Speed**: 10-100x faster than Python lists for numerical operations
- 💾 **Memory Efficient**: Uses less memory than lists
- 🎯 **Convenient**: Built-in mathematical functions

In [ ]:
# Import NumPy library
import numpy as np

# Check NumPy version
print(f"NumPy version: {np.__version__}")
print("✅ Setup complete!")

---
## 🔹 Section 2: Basic Exercises (NumPy vs Python Lists)

### Exercise 1: Understanding NumPy Arrays vs Python Lists
**Learn:** NumPy arrays are faster and more memory-efficient than Python lists for numerical operations.

#### 📖 Example:

In [ ]:
# Example: Creating a Python list and NumPy array

# Python list
python_list = [1, 2, 3, 4, 5]
print("Python List:", python_list)
print("Type:", type(python_list))

# NumPy array
numpy_array = np.array([1, 2, 3, 4, 5])
print("\nNumPy Array:", numpy_array)
print("Type:", type(numpy_array))
print("Data type:", numpy_array.dtype)

# Expected Output:
# Python List: [1, 2, 3, 4, 5]
# Type: <class 'list'>
# NumPy Array: [1 2 3 4 5]
# Type: <class 'numpy.ndarray'>
# Data type: int64

#### ✏️ Your Turn:

In [ ]:
# TODO: Create a Python list with numbers [10, 20, 30, 40, 50]
# TODO: Convert it to a NumPy array
# TODO: Print both and their types
# Hint: Use np.array() to convert list to array

# TODO: Write your code below this line
# ─────────────────────────────────────

my_list = # Your code here
my_array = # Your code here

# Print both


# ─────────────────────────────────────
# Expected Output:
# List: [10, 20, 30, 40, 50]
# Array: [10 20 30 40 50]

---
### Exercise 2: Array Creation Methods
**Learn:** NumPy provides multiple ways to create arrays quickly.

#### 📖 Example:

In [ ]:
# Example: Different ways to create NumPy arrays

# Array of zeros
zeros = np.zeros(5)
print("Zeros:", zeros)

# Array of ones
ones = np.ones(5)
print("Ones:", ones)

# Array with range of values
range_array = np.arange(0, 10, 2)  # start, stop, step
print("Range (0 to 10, step 2):", range_array)

# Array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)  # start, stop, number of values
print("Linspace (0 to 1, 5 values):", linspace_array)

# Expected Output:
# Zeros: [0. 0. 0. 0. 0.]
# Ones: [1. 1. 1. 1. 1.]
# Range (0 to 10, step 2): [0 2 4 6 8]
# Linspace (0 to 1, 5 values): [0.   0.25 0.5  0.75 1.  ]

#### ✏️ Your Turn:

In [ ]:
# TODO: Create an array of 10 zeros
# TODO: Create an array of 7 ones
# TODO: Create an array from 5 to 50 with step 5
# TODO: Create an array with 6 evenly spaced values between 0 and 100

# TODO: Write your code below
# ─────────────────────────────────────

array_zeros = # Your code here
array_ones = # Your code here
array_range = # Your code here (use np.arange)
array_linspace = # Your code here (use np.linspace)

# Print all arrays




# ─────────────────────────────────────
# Expected Output:
# Zeros: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
# Ones: [1. 1. 1. 1. 1. 1. 1.]
# Range: [ 5 10 15 20 25 30 35 40 45 50]
# Linspace: [  0.  20.  40.  60.  80. 100.]

---
### Exercise 3: Array Indexing and Slicing
**Learn:** Access and extract parts of arrays using indexing and slicing.

#### 📖 Example:

In [ ]:
# Example: Indexing and slicing NumPy arrays

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("Original array:", arr)

# Indexing (get single element)
print("First element (index 0):", arr[0])
print("Last element (index -1):", arr[-1])
print("Third element (index 2):", arr[2])

# Slicing (get multiple elements)
print("\nFirst 3 elements:", arr[0:3])  # or arr[:3]
print("Elements from index 5 to end:", arr[5:])
print("Every 2nd element:", arr[::2])
print("Reverse array:", arr[::-1])

# Expected Output:
# Original array: [ 10  20  30  40  50  60  70  80  90 100]
# First element (index 0): 10
# Last element (index -1): 100
# Third element (index 2): 30
# First 3 elements: [10 20 30]
# Elements from index 5 to end: [ 60  70  80  90 100]
# Every 2nd element: [10 30 50 70 90]
# Reverse array: [100  90  80  70  60  50  40  30  20  10]

#### ✏️ Your Turn:

In [ ]:
# TODO: Given the array below, extract:
# 1. The 5th element
# 2. Elements from index 3 to 7
# 3. Every 3rd element
# 4. Last 4 elements

numbers = np.array([5, 15, 25, 35, 45, 55, 65, 75, 85, 95])
print("Array:", numbers)

# TODO: Write your code below
# ─────────────────────────────────────

fifth_element = # Your code here
slice_3_to_7 = # Your code here
every_third = # Your code here
last_four = # Your code here

# Print results




# ─────────────────────────────────────
# Expected Output:
# 5th element: 45
# Elements 3 to 7: [35 45 55 65 75]
# Every 3rd: [ 5 35 65 95]
# Last 4: [65 75 85 95]

---
### Exercise 4: Array Reshaping
**Learn:** Change the shape of an array without changing its data.

#### 📖 Example:

In [ ]:
# Example: Reshaping arrays

# Create 1D array
arr_1d = np.arange(1, 13)
print("Original 1D array:", arr_1d)
print("Shape:", arr_1d.shape)

# Reshape to 2D (3 rows, 4 columns)
arr_2d = arr_1d.reshape(3, 4)
print("\nReshaped to 3x4:")
print(arr_2d)
print("Shape:", arr_2d.shape)

# Reshape to 2D (4 rows, 3 columns)
arr_2d_v2 = arr_1d.reshape(4, 3)
print("\nReshaped to 4x3:")
print(arr_2d_v2)

# Flatten back to 1D
arr_flat = arr_2d.flatten()
print("\nFlattened back to 1D:", arr_flat)

# Expected Output:
# Original 1D array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
# Shape: (12,)
# Reshaped to 3x4:
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
# Shape: (3, 4)

#### ✏️ Your Turn:

In [ ]:
# TODO: Create an array from 1 to 20
# TODO: Reshape it to 4 rows and 5 columns
# TODO: Reshape it to 5 rows and 4 columns
# TODO: Flatten it back to 1D

# TODO: Write your code below
# ─────────────────────────────────────

my_array = # Your code here (use np.arange)
reshaped_4x5 = # Your code here
reshaped_5x4 = # Your code here
flattened = # Your code here

# Print results
print("Original:", my_array)
print("\n4x5 shape:")

print("\n5x4 shape:")

print("\nFlattened:", flattened)

# ─────────────────────────────────────
# Expected Output:
# Original: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
# 4x5 shape:
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]]

---
### Exercise 5: Element-wise Operations
**Learn:** Perform mathematical operations on entire arrays at once.

#### 📖 Example:

In [ ]:
# Example: Element-wise operations

arr = np.array([1, 2, 3, 4, 5])
print("Original array:", arr)

# Basic arithmetic operations
print("\nAdd 10:", arr + 10)
print("Multiply by 2:", arr * 2)
print("Square each element:", arr ** 2)
print("Divide by 2:", arr / 2)

# Operations between two arrays
arr2 = np.array([10, 20, 30, 40, 50])
print("\nArray 1:", arr)
print("Array 2:", arr2)
print("Add arrays:", arr + arr2)
print("Multiply arrays:", arr * arr2)

# Expected Output:
# Original array: [1 2 3 4 5]
# Add 10: [11 12 13 14 15]
# Multiply by 2: [ 2  4  6  8 10]
# Square each element: [ 1  4  9 16 25]
# Add arrays: [11 22 33 44 55]

#### ✏️ Your Turn:

In [ ]:
# TODO: Create an array [5, 10, 15, 20, 25]
# TODO: Add 5 to each element
# TODO: Multiply each element by 3
# TODO: Calculate the square root of each element (use np.sqrt)
# TODO: Create another array [2, 4, 6, 8, 10] and subtract it from the first array

# TODO: Write your code below
# ─────────────────────────────────────

arr1 = # Your code here
add_5 = # Your code here
multiply_3 = # Your code here
square_root = # Your code here

arr2 = # Your code here
subtract_arrays = # Your code here

# Print results





# ─────────────────────────────────────
# Expected Output:
# Original: [ 5 10 15 20 25]
# Add 5: [10 15 20 25 30]
# Multiply by 3: [15 30 45 60 75]
# Square root: [2.236... 3.162... 3.872... 4.472... 5.]
# Subtract: [3 6 9 12 15]

---
### Exercise 6: Broadcasting
**Learn:** NumPy automatically broadcasts arrays of different shapes during arithmetic operations.

#### 📖 Example:

In [ ]:
# Example: Broadcasting in NumPy

# 2D array
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:")
print(matrix)

# Add a scalar (broadcasting to all elements)
print("\nAdd 10 to all elements:")
print(matrix + 10)

# Add a 1D array to each row (broadcasting)
row = np.array([10, 20, 30])
print("\nAdd [10, 20, 30] to each row:")
print(matrix + row)

# Add a column vector (broadcasting)
column = np.array([[100], [200], [300]])
print("\nAdd column to matrix:")
print(matrix + column)

# Expected Output:
# Add 10 to all elements:
# [[11 12 13]
#  [14 15 16]
#  [17 18 19]]
# Add [10, 20, 30] to each row:
# [[11 22 33]
#  [14 25 36]
#  [17 28 39]]

#### ✏️ Your Turn:

In [ ]:
# TODO: Create a 3x3 matrix with values from 1 to 9
# TODO: Multiply all elements by 5
# TODO: Create a 1D array [1, 2, 3] and add it to each row of the matrix
# TODO: Create a column array [[10], [20], [30]] and subtract it from the matrix

# TODO: Write your code below
# ─────────────────────────────────────

my_matrix = # Your code here (use np.arange and reshape)
multiply_5 = # Your code here

row_array = # Your code here
add_row = # Your code here

col_array = # Your code here
subtract_col = # Your code here

# Print results




# ─────────────────────────────────────

---
### Exercise 7: Linear Algebra - Dot Product
**Learn:** Calculate dot product of vectors and matrices.

#### 📖 Example:

In [ ]:
# Example: Dot product

# Dot product of two 1D arrays (vectors)
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
print("Vector 1:", vec1)
print("Vector 2:", vec2)

dot_product = np.dot(vec1, vec2)
print("Dot product:", dot_product)
print("Calculation: (1*4) + (2*5) + (3*6) =", 1*4 + 2*5 + 3*6)

# Alternative syntax
dot_product2 = vec1 @ vec2  # @ operator for matrix multiplication
print("Using @ operator:", dot_product2)

# Expected Output:
# Vector 1: [1 2 3]
# Vector 2: [4 5 6]
# Dot product: 32
# Calculation: (1*4) + (2*5) + (3*6) = 32

#### ✏️ Your Turn:

In [ ]:
# TODO: Create two vectors: [2, 4, 6] and [1, 3, 5]
# TODO: Calculate their dot product using np.dot()
# TODO: Verify by manual calculation
# TODO: Try using the @ operator as well

# TODO: Write your code below
# ─────────────────────────────────────

vector_a = # Your code here
vector_b = # Your code here

dot_result = # Your code here (use np.dot)
dot_result_alt = # Your code here (use @ operator)

# Manual calculation
manual = # Calculate: (2*1) + (4*3) + (6*5)

# Print results




# ─────────────────────────────────────
# Expected Output:
# Dot product: 44
# Using @: 44
# Manual: 44

---
### Exercise 8: Matrix Multiplication
**Learn:** Multiply matrices using NumPy.

#### 📖 Example:

In [ ]:
# Example: Matrix multiplication

# Create two matrices
matrix_a = np.array([[1, 2],
                     [3, 4]])
matrix_b = np.array([[5, 6],
                     [7, 8]])

print("Matrix A:")
print(matrix_a)
print("\nMatrix B:")
print(matrix_b)

# Matrix multiplication
result = np.matmul(matrix_a, matrix_b)
print("\nMatrix multiplication (A × B):")
print(result)

# Alternative: using @ operator
result2 = matrix_a @ matrix_b
print("\nUsing @ operator:")
print(result2)

# Note: matrix_a * matrix_b does ELEMENT-WISE multiplication (different!)
print("\nElement-wise multiplication (A * B):")
print(matrix_a * matrix_b)

# Expected Output:
# Matrix multiplication (A × B):
# [[19 22]
#  [43 50]]

#### ✏️ Your Turn:

In [ ]:
# TODO: Create a 2x3 matrix: [[1, 2, 3], [4, 5, 6]]
# TODO: Create a 3x2 matrix: [[7, 8], [9, 10], [11, 12]]
# TODO: Multiply them using np.matmul() or @
# TODO: Print the shapes before and after multiplication

# TODO: Write your code below
# ─────────────────────────────────────

mat_a = # Your code here (2x3 matrix)
mat_b = # Your code here (3x2 matrix)

print("Matrix A shape:", mat_a.shape)
print("Matrix B shape:", mat_b.shape)

result = # Your code here (matrix multiplication)

print("\nResult of A × B:")
print(result)
print("Result shape:", result.shape)

# ─────────────────────────────────────
# Expected Output:
# Matrix A shape: (2, 3)
# Matrix B shape: (3, 2)
# Result of A × B:
# [[ 58  64]
#  [139 154]]
# Result shape: (2, 2)

---
## 🔹 Section 3: Useful Functions

### Exercise 9: Concatenate, Split, and Stack
**Learn:** Combine and split arrays in various ways.

#### 📖 Example:

In [ ]:
# Example: Concatenate and split arrays

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9])

# Concatenate arrays
concatenated = np.concatenate([arr1, arr2, arr3])
print("Concatenated:", concatenated)

# Split array into 3 parts
split_arrays = np.split(concatenated, 3)
print("\nSplit into 3 parts:")
for i, arr in enumerate(split_arrays):
    print(f"Part {i+1}:", arr)

# Stack arrays vertically (row-wise)
stacked_v = np.vstack([arr1, arr2, arr3])
print("\nVertically stacked:")
print(stacked_v)

# Stack arrays horizontally (column-wise)
stacked_h = np.hstack([arr1, arr2, arr3])
print("\nHorizontally stacked:", stacked_h)

# Expected Output:
# Concatenated: [1 2 3 4 5 6 7 8 9]
# Split into 3 parts:
# Part 1: [1 2 3]
# Part 2: [4 5 6]
# Part 3: [7 8 9]

#### ✏️ Your Turn:

In [ ]:
# TODO: Create three arrays: [10, 20], [30, 40], [50, 60]
# TODO: Concatenate them into one array
# TODO: Split the result into 3 equal parts
# TODO: Stack the original three arrays vertically
# TODO: Stack them horizontally

# TODO: Write your code below
# ─────────────────────────────────────

a1 = # Your code here
a2 = # Your code here
a3 = # Your code here

concat = # Your code here
splits = # Your code here
v_stack = # Your code here
h_stack = # Your code here

# Print results





# ─────────────────────────────────────
# Expected Output:
# Concatenated: [10 20 30 40 50 60]
# V-Stack:
# [[10 20]
#  [30 40]
#  [50 60]]
# H-Stack: [10 20 30 40 50 60]

---
## 🔹 Section 4: Small Projects

### Project 1: Statistical Analysis of Test Scores
**Task:** Analyze a class's test scores using NumPy functions.

In [ ]:
# Project 1: Statistical Analysis

# Test scores of 20 students
scores = np.array([85, 92, 78, 90, 88, 76, 95, 89, 84, 91,
                   87, 83, 94, 79, 86, 93, 81, 88, 90, 85])

# TODO: Calculate the following statistics:
# 1. Mean (average) score
# 2. Median score
# 3. Standard deviation
# 4. Minimum and maximum scores
# 5. How many students scored above 85?
# 6. How many students scored between 80 and 90?

# TODO: Write your code below
# ─────────────────────────────────────

mean_score = # Use np.mean()
median_score = # Use np.median()
std_dev = # Use np.std()
min_score = # Use np.min()
max_score = # Use np.max()

# Count students above 85
above_85 = # Use: np.sum(scores > 85)

# Count students between 80 and 90
between_80_90 = # Use: np.sum((scores >= 80) & (scores <= 90))

# Print results
print("📊 Test Score Analysis")
print("=" * 40)
print(f"Mean Score: {mean_score:.2f}")
print(f"Median Score: {median_score:.2f}")
print(f"Standard Deviation: {std_dev:.2f}")
print(f"Min Score: {min_score}")
print(f"Max Score: {max_score}")
print(f"Students above 85: {above_85}")
print(f"Students between 80-90: {between_80_90}")

# ─────────────────────────────────────

---
### Project 2: Sales Data Analysis
**Task:** Analyze monthly sales data for a company with 3 products.

In [ ]:
# Project 2: Sales Data Analysis

# Sales data: 3 products × 12 months
# Each row = one product, each column = one month
sales_data = np.array([
    [120, 135, 142, 158, 163, 178, 185, 192, 201, 215, 225, 240],  # Product A
    [98, 105, 110, 115, 125, 132, 140, 145, 152, 158, 165, 172],   # Product B
    [150, 155, 148, 162, 170, 175, 180, 188, 195, 205, 210, 220]   # Product C
])

print("Sales Data (Products × Months):")
print(sales_data)
print("Shape:", sales_data.shape)

# TODO: Calculate:
# 1. Total sales for each product (sum across months)
# 2. Total sales for each month (sum across products)
# 3. Average monthly sales per product
# 4. Which product had the highest total sales?
# 5. Which month had the highest total sales?
# 6. Calculate percentage growth from first to last month for each product

# TODO: Write your code below
# ─────────────────────────────────────

# Total sales per product (sum along axis=1)
product_totals = # Your code here

# Total sales per month (sum along axis=0)
month_totals = # Your code here

# Average monthly sales per product
product_averages = # Your code here

# Best product (index of maximum)
best_product_idx = # Use np.argmax()

# Best month (index of maximum)
best_month_idx = # Use np.argmax()

# Growth percentage for each product
# Formula: ((last_month - first_month) / first_month) * 100
growth = # Your code here

# Print results
print("\n📈 Sales Analysis Results")
print("=" * 50)
print(f"Total Sales per Product: {product_totals}")
print(f"Total Sales per Month: {month_totals}")
print(f"Average Monthly Sales: {product_averages}")
print(f"Best Product: Product {['A', 'B', 'C'][best_product_idx]}")
print(f"Best Month: Month {best_month_idx + 1}")
print(f"Growth % (Product A, B, C): {growth}")

# ─────────────────────────────────────

---
### Project 3: Image Manipulation with NumPy
**Task:** Create and manipulate a simple "image" using NumPy arrays.

In [ ]:
# Project 3: Image Manipulation

# Create a simple 10x10 "image" (grayscale)
# Values represent pixel intensities (0 = black, 255 = white)
image = np.random.randint(0, 256, size=(10, 10))

print("Original Image (10x10):")
print(image)

# TODO: Perform the following operations:
# 1. Increase brightness by adding 50 to all pixels (clip values to max 255)
# 2. Decrease brightness by subtracting 30 from all pixels (clip values to min 0)
# 3. Create a negative image (255 - pixel_value)
# 4. Extract the center 4x4 region of the image
# 5. Flip the image vertically
# 6. Flip the image horizontally

# TODO: Write your code below
# ─────────────────────────────────────

# Increase brightness
bright_image = # Use np.clip(image + 50, 0, 255)

# Decrease brightness
dark_image = # Use np.clip(image - 30, 0, 255)

# Negative image
negative_image = # Your code here

# Extract center 4x4
center_region = # Use slicing: image[3:7, 3:7]

# Flip vertically
flip_vertical = # Use np.flip(image, axis=0)

# Flip horizontally
flip_horizontal = # Use np.flip(image, axis=1)

# Print results
print("\n🖼️ Image Manipulations")
print("=" * 50)
print("\nBrightened Image (sample):")
print(bright_image[:3, :3])  # Show top-left corner

print("\nNegative Image (sample):")
print(negative_image[:3, :3])

print("\nCenter 4x4 Region:")
print(center_region)

# ─────────────────────────────────────

---
## 🔹 Section 5: Final Challenges

### Challenge 1: Matrix Operations Combo
**Task:** Combine multiple NumPy concepts to solve this challenge.

In [ ]:
# Challenge 1: Matrix Operations Combo

# TODO: Complete the following tasks:
# 1. Create a 5x5 matrix with random integers from 1 to 50
# 2. Replace all values greater than 30 with 30
# 3. Replace all values less than 10 with 10
# 4. Calculate the sum of each row
# 5. Calculate the sum of each column
# 6. Find the overall mean of the matrix
# 7. Create a boolean mask for values greater than the mean
# 8. Count how many values are above the mean

# TODO: Write your code below
# ─────────────────────────────────────

# Step 1: Create matrix
matrix = # Use np.random.randint(1, 51, size=(5, 5))
print("Original Matrix:")
print(matrix)

# Step 2-3: Clip values
clipped_matrix = # Use np.clip(matrix, 10, 30)
print("\nClipped Matrix (10-30):")
print(clipped_matrix)

# Step 4: Row sums
row_sums = # Your code here
print("\nRow Sums:", row_sums)

# Step 5: Column sums
col_sums = # Your code here
print("Column Sums:", col_sums)

# Step 6: Overall mean
mean_value = # Your code here
print(f"\nOverall Mean: {mean_value:.2f}")

# Step 7: Boolean mask
above_mean_mask = # Your code here
print("\nAbove Mean Mask:")
print(above_mean_mask)

# Step 8: Count above mean
count_above = # Use np.sum(above_mean_mask)
print(f"\nCount Above Mean: {count_above}")

# ─────────────────────────────────────

---
### Challenge 2: Temperature Data Analysis
**Task:** Analyze temperature data for 7 days across 4 cities.

In [ ]:
# Challenge 2: Temperature Data Analysis

# Temperature data (4 cities × 7 days) in Celsius
temperatures = np.array([
    [22, 24, 23, 25, 26, 24, 23],  # City A
    [18, 19, 17, 20, 21, 19, 18],  # City B
    [30, 32, 31, 33, 34, 32, 31],  # City C
    [15, 16, 14, 17, 18, 16, 15]   # City D
])

cities = ['City A', 'City B', 'City C', 'City D']
days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun']

print("Temperature Data (°C):")
print(temperatures)

# TODO: Answer the following questions:
# 1. What is the average temperature for each city?
# 2. What is the average temperature for each day?
# 3. Which city has the highest average temperature?
# 4. Which day had the highest overall temperature?
# 5. Convert all temperatures to Fahrenheit (F = C * 9/5 + 32)
# 6. Find the temperature difference between hottest and coldest city for each day
# 7. Which city has the most stable temperature? (lowest standard deviation)

# TODO: Write your code below
# ─────────────────────────────────────

# Average per city
city_avg = # Your code here

# Average per day
day_avg = # Your code here

# Hottest city
hottest_city_idx = # Your code here

# Hottest day
hottest_day_idx = # Your code here

# Convert to Fahrenheit
temps_fahrenheit = # Your code here

# Temperature range per day
daily_max = # np.max(temperatures, axis=0)
daily_min = # np.min(temperatures, axis=0)
daily_range = # daily_max - daily_min

# Most stable city (lowest std)
city_std = # np.std(temperatures, axis=1)
stable_city_idx = # np.argmin(city_std)

# Print results
print("\n🌡️ Temperature Analysis")
print("=" * 60)
print("\nAverage Temperature per City (°C):")
for i, city in enumerate(cities):
    print(f"  {city}: {city_avg[i]:.2f}°C")

print("\nAverage Temperature per Day (°C):")
for i, day in enumerate(days):
    print(f"  {day}: {day_avg[i]:.2f}°C")

print(f"\nHottest City: {cities[hottest_city_idx]} ({city_avg[hottest_city_idx]:.2f}°C avg)")
print(f"Hottest Day: {days[hottest_day_idx]} ({day_avg[hottest_day_idx]:.2f}°C avg)")

print("\nDaily Temperature Range (°C):")
for i, day in enumerate(days):
    print(f"  {day}: {daily_range[i]:.1f}°C")

print(f"\nMost Stable City: {cities[stable_city_idx]} (std: {city_std[stable_city_idx]:.2f})")

print("\nSample Fahrenheit Conversion (City A):")
print(f"  Celsius:    {temperatures[0]}")
print(f"  Fahrenheit: {temps_fahrenheit[0]}")

# ─────────────────────────────────────

---
## 🔹 Section 6: Summary & Key Concepts

### 🎯 What You Learned Today:

**1. NumPy Basics:**
- NumPy arrays are faster and more efficient than Python lists
- Arrays have a fixed data type (dtype) for all elements
- Created arrays using `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`

**2. Indexing and Slicing:**
- Access elements: `arr[0]`, `arr[-1]`
- Slice arrays: `arr[start:stop:step]`
- Reverse arrays: `arr[::-1]`

**3. Array Reshaping:**
- `reshape()`: Change array dimensions
- `flatten()`: Convert to 1D array
- Shape must match total elements

**4. Element-wise Operations:**
- Arithmetic operations work on entire arrays
- Broadcasting allows operations on different-shaped arrays
- Much faster than Python loops!

**5. Linear Algebra:**
- Dot product: `np.dot(a, b)` or `a @ b`
- Matrix multiplication: `np.matmul(A, B)` or `A @ B`
- Element-wise multiplication: `A * B` (different from matrix multiplication!)

**6. Useful Functions:**
- `np.concatenate()`: Join arrays
- `np.split()`: Split arrays
- `np.vstack()`, `np.hstack()`: Stack arrays
- `np.mean()`, `np.std()`, `np.min()`, `np.max()`: Statistics
- `np.clip()`: Limit values to a range

---

### 📌 Key Takeaways:

✅ **NumPy is essential** for data science and machine learning  
✅ **Arrays enable vectorized operations** - no need for loops!  
✅ **Broadcasting** makes array operations flexible  
✅ **Linear algebra operations** are built-in and optimized  
✅ **Many useful functions** for data manipulation  

---

### 🚀 Next Steps:

- Practice more with NumPy's mathematical functions
- Explore advanced indexing (fancy indexing, boolean indexing)
- Learn about random number generation with NumPy
- Tomorrow: **Pandas for Data Preprocessing!**

---

### 💪 Keep Practicing!

The more you work with NumPy, the more natural it becomes. Try creating your own arrays and experimenting with different operations!

**Great job completing Day 1! 🎉**